---
title: "plan"
output: html_document
date: "2023-03-18"
---
##Introduction to Git-Hub
--> get started/ setting up Git-hub, for details take a look here: https://malikaihle.github.io/Introduction-RStudio-Git-GitHub/
--> Also look for Help at this Tutorial: https://docs.github.com/en/get-started/quickstart/hello-world
1.Forking an existing Repo
  -> "Code" -> "Open in Github Desktop" -> You now should have your own lokal version of the repository
  -> you can now upload your cloned repo in your online Git-hub
2.Creating a Branch in an existing Repo
  -> "Main" -> either choose an existing branch other than the main branch, or create a new branch (preferably with a name saying what its for)
3.Creating a new file - including a model in Lavaan
  -> "Add file" or upload code from R-Studio/ Vs Code
4.Create a pull request from the branch to the main branch
--> For detailed instructions for steps 1-4 take a look here: https://malikaihle.github.io/Collaborative-RStudio-GitHub/

5.Collaboratively combine the different models in one model all together
6.Use Issues to communicate problems that might occure 
     * tag the others in the issues to keep them updated and to make them aware of the issue
     * assign someone to a project
     * discuss the issues, using the commentary function beneath the issues
7.open PR based on those issues
     * PR reviewen
     * PR revisen
     * PR mergen
     * PR merge conflicts beheben
     * PR in project management software

You should by then be owner of your repository, should be collaborating on the merged repository, and ideally should have reviewed repositories, when issues came up(owner, collaborator, reviewer).

```{r setup, include=FALSE}
library(lavaan)
#Model 1
A ~ C
B ~ A + C

#Model 2
C ~ A
D ~ C

#Model 3
C ~ B
D ~ B + C

#Combined Model
A ~ C
B ~ A + C
C ~ A + B
D ~ B + C
```
7.Transfering the Models from lavaan into Stenograph
--> Find the Stenographs package here: https://github.com/aaronpeikert/StenoGraphs.jl
  -> open VS-Code -> create a new script and select Julia as language -> install the package

```{julia} 
import Pkg; Pkg.add("StenoGraphs")
using StenoGraphs #to select the package in julia

#Model 1
C → A
[A C] → B

#Model 2
A → C
C → D

#Model 3
B → C
[B C] → D

#Combined Model
A → B
C ⇒ A
C ⇒ B
[B C] → D

```  
  
  
